monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - fuzzrake.tracking
        - fuzzrake.security

when@dev: &when-at-dev
    monolog:
        handlers:
            main: &handler-main
                type: rotating_file
                formatter: monolog.formatter.json
                include_stacktraces: true
                level: debug
                max_files: 93
                path: "%kernel.logs_dir%/%kernel.environment%.log"

when@test: *when-at-dev

when@prod: &when-at-prod
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: warning
                handler: nested
                passthru_level: info
            nested: *handler-main

when@beta: *when-at-prod
