parameters:
  languages:
    regex_prefix: ''
    regex_suffix: ''
    replacements:
      ' with Google Translate': ' (with a translator)'
      ' ?\(native\)': ''
      'a small bit of|a bit of|bit of|a little|some|moderate|basic|elementary|slight|intermediate|beginner|limited': 'limited'

    regexp: '(?<prefix>limited\s+)?(?<language>.+)(?<suffix>\s+\(limited\))?'
