parameters:
  noPayPlans:
    regex_prefix: '^'
    regex_suffix: '$'
    replacements: # grep-payment-plans-none
      'None/100% up ?front':                'None'
      '"None, 100% upfront"':               'None'
      'None':                               'None'
      'No payment plans/100% upfront':      'None'
      '100% upfront every part':            'None'
      '100% Up ?Front\.?':                  'None'
      '1 complete payment':                 'None'

  currencies:
    regex_prefix: '(?<=^|\n)'
    regex_suffix: '(?=\n|$)'
    replacements:
      'Euro?':                              'EUR'

  paymentMethods:
    regex_prefix: '(?<=^|\n)'
    regex_suffix: '(?=\n|$)'
    replacements:
      'Apple Pay':                          'Apple Pay'
      'Bank ?trans?fers?':                  'Bank transfers'
      'BLIK':                               'BLIK'
      'Checks?':                            'Checks'
      'Cash ?app':                          'Cash App'
      'Credit cards?':                      'Credit cards'
      'Debit/credit cards?':                'Credit/debit cards'
      'Credit/debit cards?':                'Credit/debit cards'
      'Debit cards?':                       'Debit cards'
      'E-transfers?':                       'E-transfers'
      'Etsy( Payments)?':                   'Etsy Payments'
      'Google Pay':                         'Google Pay'
      'Ko-?fi':                             'Ko-fi'
      'KoronaPay':                          'KoronaPay'
      'Money ?orders?':                     'Money orders'
      'Pay ?Pal( only)?':                   'PayPal'
      'PayPal invoices?':                   'PayPal (invoices)'
      '(Transfer)?Wise(\.com)?':            'Wise'
