parameters:
  tracker_regexes:
    false_positives:
      - 'when will you start taking new COMMISSIONS'
      - 'when WE_ARE (open for|taking|take)'
      - 'when do you open for'
      - '(if|when|while)( OUR)? OFFER( are)? STATUS_ANY'

      - 'WE_ARE (now )?opening for quotes a few weeks before commission slots open'
      - '(when|if) (my |our |the )(COMMISSIONS|QUOTES) (are )?open'
      - 'after the commissions close'

      # as soon / as ... open
      - 'as (soon as WE_ARE|slots) open'

      # even though / although
      - "even though you're closed for COMMISSIONS"
      - 'although (fursuit )?COMMISSIONS are closed'

      # open in / next opening
      - 'OFFER (are )?open (in |(in )?MONTHS)'
      - 'next COMMISSIONS opening'

      # "art commissions"
      - '[^a-z]art(work)? COMMISSIONS'

    offers_statuses:
      # Start with statuses "nicely" organized into paragraphs/sentences - single spaces, no newlines, etc.
      - 'STATUS_ANY for OFFER'

      - 'OFFER(\s+are)?(\s+now)?\s+STATUS_ANY'
      - 'OFFER( are| status)?(\s+now)? ?[:-]\s*STATUS_ANY'

      # Inverted order - careful!
      - '(WE_ARE|now) STATUS_ANY(\s+for(\s+new)?|\s+new)?\s+OFFER(\s+and\s+OFFER)?'
      -              'STATUS_ANY(\s+for(\s+new)?|\s+new)\s+OFFER(\s+and\s+OFFER)?'

      - 'OPEN_TAG\s*OFFER( status:?| ?:)?\s*END_OPEN_TAGS(\s*now)?\s*STATUS_ANY'

      # Separators which should be handled safely
      - 'OPEN_TAG\s*OFFER\s+[|]\s+STATUS_ANY\s*END_TAG'

    placeholders:
      'OPEN_TAG':
        - '<(h[123456]|p|div)[^>]*>'
      'END_TAG':
        - '</(h[123456]|p|div)>'

      'END_OPEN_TAGS':
        - 'END_TAG\s*OPEN_TAG'
        - 'END_TAG\s*END_TAG\s*OPEN_TAG\s*OPEN_TAG'
        - 'END_TAG\s*END_TAG\s*END_TAG\s*OPEN_TAG\s*OPEN_TAG\s*OPEN_TAG'

      'STATUS_ANY':
        - 'STATUS_OPEN'
        - 'STATUS_CLOSED'

      'STATUS_OPEN=status_open':
        - 'open(?!ing)'
        - 'only making'
        - 'taking'

      'STATUS_CLOSED=status_closed':
        - 'closed?'
        - 'not (taking( on)?|accepting|open)'
        - "don't (do|take|provide|accept)"

      'OFFER':
        'HANDPAWS_AND_SOCKPAWS=handpaws_cms_and_sockpaws_cms':
          - 'handpaws AND sockpaws COMMISSIONS'

        'PARTS_AND_REFURBISHMENTS=parts_and_refurbishments':
          - 'parts AND refurbishments COMMISSIONS'

        'COMMISSIONS_AND_QUOTES=commissions_and_quotes':
          - '(COMMISSIONS AND quotes?)'
          - '(quotes? AND COMMISSIONS)'

        'FULLSUIT_COMMISSIONS=fullsuit_commissions':
          - 'fullsuit COMMISSIONS'

        'PARTIAL_COMMISSIONS=partial_commissions':
          - 'partial COMMISSIONS'

        'HEAD_COMMISSIONS=head_commissions':
          - 'head COMMISSIONS'

        'PARTS=parts':
          - '(fursuit )?parts? COMMISSIONS'

        'COMPLEX_COMMISSIONS_WORDING=commissions':
          - '(custom )?(costume |fursuit )?COMMISSIONS'
          - '(custom |COMMISSIONS )?slots?'
          - 'fursuits?( queue)?'

        'PROJECTS=projects':
          - 'projects?'

        'TRADES=trades':
          - 'trades?'

        'REFURBISHMENTS=refurbishments':
          - 'refurbishments?'

        'PRE_MADES=pre_mades':
          - 'pre-?mades?( designs?)?'

        'ARTISTIC_LIBERTY=artistic_liberty':
          - 'artistic liberty'

        'QUOTES=quotes':
          - 'quotes?'

        'ORDERS=orders':
          - '(custom )?orders?'

      ' AND ':
        - ' and '
        - ' ?(&amp;|/) ?'

      'COMMISSIONS':
        - 'comm?iss?ions?'
        - 'comms'

      'WE_ARE':
        - "we( are|'re| will)?"
        - "i( am|'m| will)?"
        - "STUDIO_NAME (is|are)"

      'OUR':
        - 'my'
        - 'mine'
        - 'ours?'

      'MONTHS':
        - 'jan(uary)?'
        - 'feb(ruary)?'
        - 'mar(ch)?'
        - 'apr(il)?'
        - 'may'
        - 'june?'
        - 'july?'
        - 'aug(ust)?'
        - 'sep(tember)?'
        - 'oct(ober)?'
        - 'nov(ember)?'
        - 'dec(ember)?'

    cleaners: # Used to remove noise / simplify information
      '(?<=function|try|if|catch|else[;,{})]) (?=function|catch|else[{}\$(])': '_'
      '(?<=return|delete) (?=this)':                                           '_'
      '<script[^>]*>[^ ]+</script>':                                           ' '
      '<meta (?:itemprop|property)="(?:og:|twitter:)?description"[^>]+>':      ' ' # Seems to duplicate primary content

      '&nbsp;':                                          ' '
      "\u00A0":                                          ' ' # NBSP
      '<br */?>':                                        "\n"
      '<style[^>]*>.*?</style>':                         ' '
      '<!--.*?-->':                                      ' '
      '</?(?:strong|b|i|span|center|u|a|em|font)[^>]*>': ''
      '\*\*\*open\*\*\*':                                'open'
      '&gt;&gt;open&lt;&lt;':                            'open'
      '(<[^>]+ )style="[^"]*"([^>]*>)':                  '$1$2'

      '&#(?:39|8217);': "'"

      '\t':     ' '
      ' {2,}':  ' '
      '\n{2,}': "\n"

      # square.site
      # {"content":{"quill":{"ops":[{"insert":"Fursuit commissions are currently OPEN\n"}]}}}
      ',"attributes":\{[^}]*\}': ''
      '"\},\{"insert":"':        ''

      # always / currently / now
      '(?<![a-z])(currently|basically always|always)(?![a-z])': 'now'

      # Change order to reduce number of alterations
      '(?<![a-z])we are now(?![a-z])': 'now we are'
      '(?<![a-z])not now(?![a-z])':    'now not'

      # [ Commissions . . . Open ]
      '\[ ([a-z]+) ?\.(?: ?\.)+ ?([a-z]+) \]': '$1: $2'

      # | - Commissions: - CLOSED |
      '\| - ([a-z]+): - ([a-z]+) \|': '$1: $2'
