parameters:
  tracker_regexes:
    false_positives:
      - 'next C___S opening (estimated|will)'
      - '(if|when|while) OFFER (are )?STATUS_ANY'
      - 'when WE_ARE DOING_STUFF_FALSE_POSITVES'
      - 'when will you start taking new C___S'
      - 'when do you open for commissions/quotes'
      - '(when|if) (my |our |the )(COMMISSIONS|QUOTES) (are )?open'
      - 'after the commissions close'
      - "even though you're closed for C___S"
      - 'although (fursuit )?C___S are closed'
      - '(quotes|C___S) open (in |(in )?MONTHS)'
      - 'slots are open in'
      - 'as (soon as WE_ARE|slots) open'
      - '[^a-z]art(work)? C___S( are:?| ?:)' # "art commissions"
      - 'OFFER status: STATUS_ANY ?</h1>\s*<h1[^>]*> ?MONTHS'
      - 'WE_ARE (now )?opening for quotes a few weeks before commission slots open'

    offer_statuses:
      - "(?P<status_open>you can still submit a QUOTES form if you're interested)"
      - 'WE_ARE STATUS_ANY COMMISSIONS'
      - '(C___S\s*[:-]\s*)?STATUS_ANY for (new )?OFFER'
      - 'OFFER( status| NOW)?([ :_-]+\s*?)STATUS_ANY' # - and _ should work for attributes as well
      - 'OFFER\s+(are:?|basically)\s+(NOW:?\s+)?(&gt;&gt;)?STATUS_ANY' # "(&gt;&gt;)?" - tc057
      - 'STATUS_ANY new OFFER'
      - 'NOW we are STATUS_ANY for a handful of OFFER' # WTF
      - 'NOW\s+STATUS_ANY\s+(new\s+|for\s+)?OFFER'
      - 'we STATUS_ANY OFFER'
      - '\[ OFFER[. ]+STATUS_ANY \]' # tc045
      - '<h2[^>]*> ?OFFER \| STATUS_ANY ?</h2>'
      - '<h2[^>]*> ?OFFER(( status:?| ?:)) ?</h2>\s*<h2[^>]*> ?STATUS_ANY' # No closing </h2> for any comments
      - '<h4[^>]*> ?OFFER(( status:?| ?:))? ?</h4>\s*<h4[^>]*> ?STATUS_ANY' # No closing </h4> for any comments
      - '<p[^>]*> ?OFFER(( status:?| ?:))? ?</p>\s*<p[^>]*> ?(NOW )?STATUS_ANY' # No closing </p> for any comments
      - '<h2[^>]*> ?OFFER(( status:?| ?:))? ?</h2>\s*<p[^>]*> ?(NOW )?STATUS_ANY' # No closing </p> for any comments
      - 'OFFER(( status:?| ?:))?\s*</h1>\s*</div>\s*<div[^>]*>\s*<p[^>]*>\s*STATUS_ANY'

    placeholders:
      'STATUS_ANY':
        - 'STATUS_OPEN'
        - 'STATUS_CLOSED'

      'STATUS_OPEN':
        - '?P<status_open>' # TODO: make the group name in some other way...
        - 'open(?!ing)'
        - 'only making'
        - 'taking'

      'STATUS_CLOSED':
        - '?P<status_closed>'
        - 'closed?'
        - 'not (NOW )?(taking on|accepting|open for)'
        - "don't (do|take|provide)"

      'OFFER':
        - 'HANDPAWS&SOCKPAWS':
            - '?P<hadpaws_and_sockpaws_commissions>'
            - 'handpaws_AND_sockpaws C___S'
        - 'PARTS&REFURBISHMENTS':
            - '?P<parts_and_refurbishments>'
            - 'parts_AND_refurbishments C___S'
        - 'COMMISSIONS&QUOTES':
            - '?P<commissions_and_quotes>'
            - '(C___S_AND_quotes?)'
            - '(quotes?_AND_C___S)'
        - 'FULLSUIT_COMMISSIONS':
            - '?P<fullsuit_commissions>'
            - 'fullsuit C___S'
        - 'PARTIAL_COMMISSIONS':
            - '?P<partial_commissions>'
            - 'partial C___S'
        - 'HEAD_COMMISSIONS':
            - '?P<head_commissions>'
            - 'head C___S'
        - 'PARTS':
            - '?P<parts>'
            - '(fursuit )?parts? C___S'
        - 'COMMISSIONS':
            - '?P<commissions>'
            - '(custom )?(costume |fursuit )?C___S'
            - '(custom |C___S )?slots?'
            - 'fursuits?( queue)?'
            - 'comms'
            - 'current mode' # tc052
            - 'projects'
        - 'TRADES':
            - '?P<trades>'
            - 'trades?'
        - 'REFURBISHMENTS':
            - '?P<refurbishments>'
            - 'refurbishments?'
        - 'PRE-MADES':
            - '?P<premades>'
            - 'pre-?mades?( designs?)?'
        - 'ARTISTIC_LIBERTY':
            - '?P<artistic_liberty>'
            - 'artistic liberty'
        - 'QUOTES':
            - '?P<quotes>'
            - 'quotes?'
        - 'ORDERS':
            - '?P<orders>'
            - '(custom )?orders?'

      '_AND_':
        - ' and '
        - ' ?(&amp;|/) ?'

      'C___S': 'comm?iss?ions?' # Not including "comms"

      'NOW':
        - 'currently'
        - 'now'
        - 'always'

      'WE_ARE':
        - "we( are|'re| will)?"
        - "i( am|'m| will)?"

      'MONTHS':
        - 'jan(uary)?'
        - 'feb(ruary)?'
        - 'mar(ch)?'
        - 'apr(il)?'
        - 'may'
        - 'june?'
        - 'july?'
        - 'aug(ust)?'
        - 'sep(tember)?'
        - 'oct(ober)?'
        - 'nov(ember)?'
        - 'dec(ember)?'

      'DOING_STUFF_FALSE_POSITVES':
        - 'open for'
        - 'taking'
        - 'take'

    matched_group_name_to_offers_or_status:
      'status_open':
        - 'STATUS:OPEN' # grep-offer-status-constants
      'status_closed':
        - 'STATUS:CLOSED' # grep-offer-status-constants

      'hadpaws_and_sockpaws_commissions':
        - 'HANDPAWS COMMISSIONS'
        - 'SOCKPAWS COMMISSIONS'
      'parts_and_refurbishments':
        - 'PARTS'
        - 'REFURBISHMENTS'
      'commissions_and_quotes':
        - 'COMMISSIONS'
        - 'QUOTES'
      'fullsuit_commissions':
        - 'FULLSUIT COMMISSIONS'
      'partial_commissions':
        - 'PARTIAL COMMISSIONS'
      'head_commissions':
        - 'HEAD COMMISSIONS'
      'parts':
        - 'PARTS'
      'commissions':
        - 'COMMISSIONS'
      'trades':
        - 'TRADES'
      'refurbishments':
        - 'REFURBISHMENTS'
      'premades':
        - 'PRE-MADES'
      'artistic_liberty':
        - 'ARTISTIC LIBERTY'
      'quotes':
        - 'QUOTES'
      'orders':
        - 'ORDERS'

    cleaners: # Used to remove noise / simplify information
      '(?<=function|try|if|catch|else[;,{})]) (?=function|catch|else[{}\$(])': '_'
      '(?<=return|delete) (?=this)':                                           '_'
      '<script[^>]*>[^ ]+</script>':                                           ' '
      '<meta (?:itemprop|property)="(?:og:|twitter:)?description"[^>]+>':      ' ' # Seems to duplicate primary content

      '&nbsp;':                                          ' '
      "\u00A0":                                          ' ' # NBSP
      '<br */?>':                                        "\n"
      '<style[^>]*>.*?</style>':                         ' '
      '<!--.*?-->':                                      ' '
      '</?(?:strong|b|i|span|center|u|a|em|font)[^>]*>': ''
      '\*\*\*OPEN\*\*\*':                                'open'
      '(<[^>]+ )style="[^"]*"([^>]*>)':                  '$1$2'

      '&#(?:39|8217);': "'"

      '  +':   ' '
      "\n\n+": "\n"

      # square.site
      # {"content":{"quill":{"ops":[{"insert":"Fursuit commissions are currently OPEN\n"}]}}}
      ',"attributes":\{[^}]*\}': ''
      '"\},\{"insert":"':        ''
