parameters:
  tracker_regexes:
    false_positives:
      - 'next COMMISSIONS opening'
      - '(if|when|while)( OUR)? OFFER( are)? STATUS_ANY'

      - 'when will you start taking new COMMISSIONS'
      - 'when WE_ARE DOING_STUFF_FALSE_POSITVES'
      - 'when do you open for'
      - '(when|if) (my |our |the )(COMMISSIONS|QUOTES) (are )?open'
      - 'after the commissions close'
      - "even though you're closed for COMMISSIONS"
      - 'although (fursuit )?COMMISSIONS are closed'
      - '(quotes|COMMISSIONS) open (in |(in )?MONTHS)'
      - 'OFFER (are )?open in'
      - 'as (soon as WE_ARE|slots) open'
      - '[^a-z]art(work)? COMMISSIONS' # "art commissions"
      - 'OFFER status: STATUS_ANY ?</h1>\s*<h1[^>]*> ?MONTHS'
      - 'WE_ARE (now )?opening for quotes a few weeks before commission slots open'

    offers_statuses:
      # Commissions/Quotes Currently Closed
      - 'OFFER(\s+are)?(\s+now)?\s+STATUS_ANY'
      - 'OFFER( are| status)?(\s+now)? ?[:-]\s*STATUS_ANY'

      # Inverted order - careful!
      - '(WE_ARE|now) STATUS_ANY(\s+for|\s+new)?\s+OFFER'
      - 'STATUS_ANY(\s+for(\s+new)?|\s+new)\s+OFFER'

      - 'OPEN_TAG\s*OFFER( status:?| ?:)?\s*END_OPEN_TAGS(\s*now)?\s*STATUS_ANY'

      # Separators which should be handled safely
      - 'OPEN_TAG\s*OFFER\s+[|]\s+STATUS_ANY\s*END_TAG'

    placeholders:
      'OPEN_TAG':
        - '<(h[123456]|p|div)[^>]*>'
      'END_TAG':
        - '</(h[123456]|p|div)>'

      'END_OPEN_TAGS':
        - 'END_TAG\s*OPEN_TAG'
        - 'END_TAG\s*END_TAG\s*OPEN_TAG\s*OPEN_TAG'
        - 'END_TAG\s*END_TAG\s*END_TAG\s*OPEN_TAG\s*OPEN_TAG\s*OPEN_TAG'

      'STATUS_ANY':
        - 'STATUS_OPEN'
        - 'STATUS_CLOSED'

      '?P<status_open>STATUS_OPEN':
        - 'open(?!ing)'
        - 'only making'
        - 'taking'

      '?P<status_closed>STATUS_CLOSED':
        - 'closed?'
        - 'not (taking( on)?|accepting|open)'
        - "don't (do|take|provide|accept)"

      'OFFER':
        '?P<handpaws_cms_and_sockpaws_cms>HANDPAWS_AND_SOCKPAWS':
          - 'handpaws AND sockpaws COMMISSIONS'

        '?P<parts_and_refurbishments>PARTS_AND_REFURBISHMENTS':
          - 'parts AND refurbishments COMMISSIONS'

        '?P<commissions_and_quotes>COMMISSIONS_AND_QUOTES':
          - '(COMMISSIONS AND quotes?)'
          - '(quotes? AND COMMISSIONS)'

        '?P<fullsuit_commissions>FULLSUIT_COMMISSIONS':
          - 'fullsuit COMMISSIONS'

        '?P<partial_commissions>PARTIAL_COMMISSIONS':
          - 'partial COMMISSIONS'

        '?P<head_commissions>HEAD_COMMISSIONS':
          - 'head COMMISSIONS'

        '?P<parts>PARTS':
          - '(fursuit )?parts? COMMISSIONS'

        '?P<commissions>COMPLEX_COMMISSIONS_WORDING':
          - '(custom )?(costume |fursuit )?COMMISSIONS'
          - '(custom |COMMISSIONS )?slots?'
          - 'fursuits?( queue)?'

        '?P<projects>PROJECTS':
          - 'projects?'

        '?P<trades>TRADES':
          - 'trades?'

        '?P<refurbishments>REFURBISHMENTS':
          - 'refurbishments?'

        '?P<pre_mades>PRE_MADES':
          - 'pre-?mades?( designs?)?'

        '?P<artistic_liberty>ARTISTIC_LIBERTY':
          - 'artistic liberty'

        '?P<quotes>QUOTES':
          - 'quotes?'

        '?P<orders>ORDERS':
          - '(custom )?orders?'

      ' AND ':
        - ' and '
        - ' ?(&amp;|/) ?'

      'COMMISSIONS':
        - 'comm?iss?ions?'
        - 'comms'

      'WE_ARE':
        - "we( are|'re| will)?"
        - "i( am|'m| will)?"
        - "STUDIO_NAME (is|are)"

      'OUR':
        - 'my'
        - 'mine'
        - 'ours?'

      'MONTHS':
        - 'jan(uary)?'
        - 'feb(ruary)?'
        - 'mar(ch)?'
        - 'apr(il)?'
        - 'may'
        - 'june?'
        - 'july?'
        - 'aug(ust)?'
        - 'sep(tember)?'
        - 'oct(ober)?'
        - 'nov(ember)?'
        - 'dec(ember)?'

      'DOING_STUFF_FALSE_POSITVES':
        - 'open for'
        - 'taking'
        - 'take'

    cleaners: # Used to remove noise / simplify information
      '(?<![a-z])(currently|basically always|always)(?![a-z])': 'now'

      # Change order to reduce number of alterations
      '(?<![a-z])we are now(?![a-z])': 'now we are'
      '(?<![a-z])not now(?![a-z])':    'now not'

      '(?<=function|try|if|catch|else[;,{})]) (?=function|catch|else[{}\$(])': '_'
      '(?<=return|delete) (?=this)':                                           '_'
      '<script[^>]*>[^ ]+</script>':                                           ' '
      '<meta (?:itemprop|property)="(?:og:|twitter:)?description"[^>]+>':      ' ' # Seems to duplicate primary content

      '&nbsp;':                                          ' '
      "\u00A0":                                          ' ' # NBSP
      '<br */?>':                                        "\n"
      '<style[^>]*>.*?</style>':                         ' '
      '<!--.*?-->':                                      ' '
      '</?(?:strong|b|i|span|center|u|a|em|font)[^>]*>': ''
      '\*\*\*open\*\*\*':                                'open'
      '&gt;&gt;open&lt;&lt;':                            'open'
      '(<[^>]+ )style="[^"]*"([^>]*>)':                  '$1$2'

      '&#(?:39|8217);': "'"

      '\t':    ' '
      '  +':   ' '
      '\n\n+': "\n"

      # [ Commissions . . . Open ]
      '\[ ([a-z]+) ?\.(?: ?\.)+ ?([a-z]+) \]': '$1: $2'

      # | - Commissions: - CLOSED |
      '\| - ([a-z]+): - ([a-z]+) \|': '$1: $2'

      # square.site
      # {"content":{"quill":{"ops":[{"insert":"Fursuit commissions are currently OPEN\n"}]}}}
      ',"attributes":\{[^}]*\}': ''
      '"\},\{"insert":"':        ''
