---
php_fpm_docker_image_name: 'fuzzrake/php-fpm:latest'

systemd_service_name:      'messenger-worker-{{ server_name }}'
systemd_service_conf_path: '/etc/systemd/system/{{ systemd_service_name }}.service'
