parameters:
  strings:
    regex_prefix: ''
    regex_suffix: ''
    replacements:
      '’':                        "'"
      '^-$':                      ''
      '^Rather not say$':         ''
      '^n/a$':                    ''
      '^no\.$':                   ''
      '^n/a yet$':                ''
      '[ \t]{2,}':                ' '

  lists:
    regex_prefix: '(?<=^|\n)'
    regex_suffix: '(?=\n|$)'
    replacements:
      '(^|\\s)LED($|\\s)':                           '$1LED$2'
      'Arm ?sleeves':                                'Arm sleeves'
      'backpacks':                                   'Backpacks'
      'Bandannas':                                   'Bandanas'
      '(.+)changable(.+)':                           '$1changeable$2'
      'claws':                                       'Claws'
      'Dry brushing':                                'Drybrushing'
      'Femme Suits':                                 'Femme suits'
      'Foam Bases':                                  'Foam bases'
      'Fursuit Props':                               'Fursuit props'
      'Fursuit Sneakers':                            'Fursuit sneakers'
      'Fursuit Sprays?':                             'Fursuit sprays'
      'Head ?Bases':                                 'Head bases'
      'Hidden pockets?':                             'Hidden pocket'
      'Just Ask':                                    'Just ask'
      'Legsleeves':                                  'Leg sleeves'
      'Pickable Noses?':                             'Pickable nose'
      'Plush Suits':                                 'Plush suits'
      'Plush Claws':                                 'Plush claws'
      'Plushes':                                     'Plushies'
      '(p)ose?able':                                 '$1oseable'
      'Pose?able tou?ngu?es?':                       'Poseable tongue'
      'Removable Eyelids':                           'Removable eyelids'
      'Removable Eyes':                              'Removable eyes'
      'Sock paws':                                   'Sockpaws'
      'Toony Foam Bases':                            'Toony foam bases'
      'Premade Props':                               'Premade props'
      'Refurbishing':                                'Refurbishments'
      'Zipper tails?':                               'Zipper tails'
