parameters:
  languages:
    regex_prefix: ''
    regex_suffix: ''
    replacements:
      ' \(?with( a)? (Google Translate|translator)\)?': ' (with a translator)'
      ' ?\(native\)': ''
      'a( small| little)?( bit)? of': 'a little'
      'bit of|a little|some|moderate|basic|elementary|slight|intermediate|beginner|limited': 'limited'

    regexp: '(?<prefix>limited\s+)?(?<language>.+)(?<suffix>\s+\(limited\))?'
