parameters:
  urls:
    regex_prefix: ''
    regex_suffix: ''
    replacements:
      '\?fbclid=[^&]+(.+)?$': '?$1'
      '\?$': ''

      '^(no|n/a)$': ''

      '^(?:https?://)?(?:www\.)?instagram\.com/(.+)?$': 'https://www.instagram.com/$1'
      '^https://www\.instagram\.com/([^?/]+)/?(?:\?.+)?$': 'https://www.instagram.com/$1/'

      '//x\.com/': '//twitter.com/'
      '^(?:https?://)?(?:www\.|mobile\.)?twitter\.com/([^/?]+(/status/.+)?).*$': 'https://twitter.com/$1'

      '^(?:https?://)?(?:www\.|m\.|business\.)?facebook\.com/(pg/)?([^/?]+)(/posts|/about)?/?(\?(?!id=)[a-z_]+=[a-z_0-9]+)?$': 'https://www.facebook.com/$1$2$3/'
      '^https://www\.facebook\.com/profile\.php\?id=(\d+)&ref=tn_tnmn$': 'https://www.facebook.com/profile.php?id=$1'

      '^(?:https?://)?(?:www\.)?furaffinity(?:\.net|\.com)?/(?:user/|gallery/)?([^/]+)/?$': 'https://www.furaffinity.net/user/$1/'

      '^(?:https?://)?(?:(?:www|m)\.)?youtube\.com/': 'https://www.youtube.com/'
      '^https://www\.youtube\.com/((?:channel|user|c)/[^/?]+)(?:/featured|/videos)?(/|\?view_as=subscriber)?$': 'https://www.youtube.com/$1'
      '^https://www\.youtube\.com/@([^?]+).*$': 'https://www.youtube.com/@$1'

      '^(?:https?://)?(?:www\.)?deviantart(?:\.net|\.com)?/([^/]+)(?:/gallery)?/?$': 'https://www.deviantart.com/$1'
      '^(?:https?://)?(?:www\.)?([^.]+)\.deviantart(?:\.net|\.com)?/?$': 'https://$1.deviantart.com/'

      '^(?:https?://)?(?:www\.)?etsy\.com/people/([^?]+)(?:\?ref=[-a-z_0-9]+)?$': 'https://www.etsy.com/people/$1'
      '^(?:https?://)?(?:www\.)?etsy\.com/(?:[a-z]{2}/)?shop/([^?]+)(?:\?ref=[-a-z_0-9]+)?$': 'https://www.etsy.com/shop/$1'

      '^http://([a-z]+)\.tumblr\.com/': 'https://$1.tumblr.com/'

      '^(?:https?://)?(?:www\.)?fursuitreview\.com/maker/([^/]+)/$': 'https://fursuitreview.com/m/$1/'

      '^(?:https?://)?(?:www\.)?furtrack\.com/user/([^/]+)(?:/uploads|/)?$': 'https://www.furtrack.com/user/$1'
      '^https://www.furtrack.com/index/maker:[^/]+/(\d+)$': 'https://www.furtrack.com/p/$1'
      '^https://orca2.furtrack.com/gallery/\d+/(\d+)-[a-f0-9]+\.jpg$': 'https://www.furtrack.com/p/$1'

      '^https://www\.furtrack\.com/index/([^:/]+)$': 'https://www.furtrack.com/index/maker:$1'
      '^https://www\.furtrack\.com/user/[^/]+/uploads/(\d+)$': 'https://www.furtrack.com/p/$1'
      '^https://www\.furtrack\.com/user/[^/]+/crafting/(\d+)$': 'https://www.furtrack.com/p/$1'
