---
- name: 'Run: gradlew distTar (locally)'
  ansible.builtin.command:
    chdir:      '../kotlin'
    cmd:        './gradlew distTar'
  changed_when: '"executed" in gradlew_result.stdout'
  check_mode:   false
  delegate_to:  'localhost'
  register:     'gradlew_result'

- name: 'Assure remote backend directory exists'
  ansible.builtin.file:
    group:   '{{ user_group }}'
    mode:    '0700'
    owner:   '{{ user_name }}'
    path:    '{{ backend_deployment_path }}'
    recurse: true
    state:   'directory'

- name: 'Copy the distribution tar'
  ansible.builtin.copy:
    dest:  '{{ backend_deployment_path }}/dist.tar'
    group: '{{ user_group }}'
    mode:  '0600'
    owner: '{{ user_name }}'
    src:   '../kotlin/build/distributions/fuzzrake-git-HEAD.tar'

- name: 'Extract the distribution tar'
  ansible.builtin.unarchive:
    dest:       '{{ backend_deployment_path }}'
    group:      '{{ user_group }}'
    mode:       '0700'
    owner:      '{{ user_name }}'
    remote_src: true
    src:        '{{ backend_deployment_path }}/dist.tar'

- name: 'Create configuration file'
  ansible.builtin.template:
    dest:  '{{ backend_deployment_path }}/fuzzrake-config.yaml'
    group: '{{ user_group }}'
    mode:  '0600'
    owner: '{{ user_name }}'
    src:   'fuzzrake-config.yaml.j2'
